apiVersion: v1
kind: Service
metadata:
  labels:
    app: selenium-firefox
  name: selenium-firefox
spec:
  ports:
  - port: 4444
    protocol: TCP
    targetPort: 4444
    name: control
  - port: 7900
    protocol: TCP
    targetPort: 7900
    name: vnc
  selector:
    app: selenium-firefox
  type: NodePort
